# Copyright 2017 ahahn94
# This program is published under the GNU GPL v.2
#
# kali_remove uninstalls all of the default pentesting tools from kali linux.
# This results in a general purpose debian install, but with a rolling release.
#
#!/bin/bash
sudo apt-get remove kali-linux-full
sudo apt-get remove kali-linux
sudo apt-get remove 0trace
sudo apt-get remove acccheck
sudo apt-get remove ace-voip
sudo apt-get remove afflib-tools
sudo apt-get remove aircrack-ng
sudo apt-get remove amap
sudo apt-get remove apache-users
sudo apt-get remove apktool
sudo apt-get remove armitage
sudo apt-get remove arping
sudo apt-get remove iputils-arping
sudo apt-get remove arpwatch
sudo apt-get remove arp-scan
sudo apt-get remove asleap
sudo apt-get remove automater
sudo apt-get remove autopsy
sudo apt-get remove backdoor-factory
sudo apt-get remove bbqsql
sudo apt-get remove bdfproxy
sudo apt-get remove bed
sudo apt-get remove beef-xss
sudo apt-get remove binwalk
sudo apt-get remove blindelephant
sudo apt-get remove bluelog
sudo apt-get remove blueranger
sudo apt-get remove bluesnarfer
sudo apt-get remove bluez
sudo apt-get remove bluez-hcidump
sudo apt-get remove braa
sudo apt-get remove btscanner
sudo apt-get remove bully
sudo apt-get remove bulk-extractor
sudo apt-get remove burpsuite
sudo apt-get remove cabextract
sudo apt-get remove cadaver
sudo apt-get remove casefile
sudo apt-get remove cdpsnarf
sudo apt-get remove cewl
sudo apt-get remove cgpt
sudo apt-get remove chirp
sudo apt-get remove chkrootkit
sudo apt-get remove chntpw
sudo apt-get remove cisco-auditing-tool
sudo apt-get remove cisco-global-exploiter
sudo apt-get remove cisco-ocs
sudo apt-get remove cisco-torch
sudo apt-get remove clang
sudo apt-get remove clusterd
sudo apt-get remove cmospwd
sudo apt-get remove commix
sudo apt-get remove copy-router-config
sudo apt-get remove cowpatty
sudo apt-get remove creddump
sudo apt-get remove cryptsetup
sudo apt-get remove crunch
sudo apt-get remove cryptcat
sudo apt-get remove curlftpfs
sudo apt-get remove cutycapt
sudo apt-get remove cymothoa
sudo apt-get remove darkstat
sudo apt-get remove davtest
sudo apt-get remove dbd
sudo apt-get remove dc3dd
sudo apt-get remove dcfldd
sudo apt-get remove ddrescue
sudo apt-get remove deblaze
sudo apt-get remove dex2jar
sudo apt-get remove dhcpig
sudo apt-get remove dirb
sudo apt-get remove dirbuster
sudo apt-get remove dissy
sudo apt-get remove dmitry
sudo apt-get remove dnmap
sudo apt-get remove dns2tcp
sudo apt-get remove dnschef
sudo apt-get remove dnsenum
sudo apt-get remove dnsmap
sudo apt-get remove dnsrecon
sudo apt-get remove dnstracer
sudo apt-get remove dnswalk
sudo apt-get remove dos2unix
sudo apt-get remove dotdotpwn
sudo apt-get remove dradis
sudo apt-get remove driftnet
sudo apt-get remove dsniff
sudo apt-get remove dumpzilla
sudo apt-get remove doona
sudo apt-get remove eapmd5pass
sudo apt-get remove edb-debugger
sudo apt-get remove enum4linux
sudo apt-get remove enumiax
sudo apt-get remove ethtool
sudo apt-get remove ettercap-graphical
sudo apt-get remove ewf-tools
sudo apt-get remove exiv2
sudo apt-get remove exploitdb
sudo apt-get remove extundelete
sudo apt-get remove fcrackzip
sudo apt-get remove fern-wifi-cracker
sudo apt-get remove fierce
sudo apt-get remove fiked
sudo apt-get remove fimap
sudo apt-get remove findmyhash
sudo apt-get remove flasm
sudo apt-get remove foremost
sudo apt-get remove fping
sudo apt-get remove fragroute
sudo apt-get remove fragrouter
sudo apt-get remove framework2
sudo apt-get remove ftester
sudo apt-get remove funkload
sudo apt-get remove galleta
sudo apt-get remove gdb
sudo apt-get remove gdb-minimal
sudo apt-get remove gdb-python2
sudo apt-get remove ghost-phisher
sudo apt-get remove giskismet
sudo apt-get remove golismero
sudo apt-get remove gpp-decrypt
sudo apt-get remove grabber
sudo apt-get remove guymager
sudo apt-get remove hackrf
sudo apt-get remove hamster-sidejack
sudo apt-get remove hash-identifier
sudo apt-get remove hashcat
sudo apt-get remove hashcat-utils
sudo apt-get remove hexinject
sudo apt-get remove hexorbase
sudo apt-get remove hashid
sudo apt-get remove hotpatch
sudo apt-get remove hping3
sudo apt-get remove httrack
sudo apt-get remove hydra
sudo apt-get remove hydra-gtk
sudo apt-get remove i2c-tools
sudo apt-get remove iaxflood
sudo apt-get remove ifenslave
sudo apt-get remove ike-scan
sudo apt-get remove imagemagick
sudo apt-get remove graphicsmagick-imagemagick-compat
sudo apt-get remove imagemagick-6.q16
sudo apt-get remove inetsim
sudo apt-get remove intersect
sudo apt-get remove intrace
sudo apt-get remove inviteflood
sudo apt-get remove iodine
sudo apt-get remove irpas
sudo apt-get remove jad
sudo apt-get remove javasnoop
sudo apt-get remove jboss-autopwn
sudo apt-get remove john
sudo apt-get remove johnny
sudo apt-get remove joomscan
sudo apt-get remove jsql
sudo apt-get remove keepnote
sudo apt-get remove keimpx
sudo apt-get remove killerbee
sudo apt-get remove king-phisher
sudo apt-get remove kismet
sudo apt-get remove laudanum
sudo apt-get remove lbd
sudo apt-get remove leafpad
sudo apt-get remove libfindrtp
sudo apt-get remove libfreefare-bin
sudo apt-get remove libhivex-bin
sudo apt-get remove libnfc-bin
sudo apt-get remove lynis
sudo apt-get remove macchanger
sudo apt-get remove magicrescue
sudo apt-get remove magictree
sudo apt-get remove maltegoce
sudo apt-get remove maltego-teeth
sudo apt-get remove maskprocessor
sudo apt-get remove masscan
sudo apt-get remove mc
sudo apt-get remove hashdeep
sudo apt-get remove mdbtools
sudo apt-get remove mdk3
sudo apt-get remove medusa
sudo apt-get remove memdump
sudo apt-get remove metasploit-framework
sudo apt-get remove mfcuk
sudo apt-get remove mfoc
sudo apt-get remove mfterm
sudo apt-get remove mimikatz
sudo apt-get remove minicom
sudo apt-get remove miranda
sudo apt-get remove miredo
sudo apt-get remove missidentify
sudo apt-get remove mitmproxy
sudo apt-get remove msfpc
sudo apt-get remove multimac
sudo apt-get remove nasm
sudo apt-get remove nbtscan
sudo apt-get remove ncat-w32
sudo apt-get remove ncrack
sudo apt-get remove ncurses-hexedit
sudo apt-get remove netdiscover
sudo apt-get remove netmask
sudo apt-get remove netsed
sudo apt-get remove netsniff-ng
sudo apt-get remove netwag
sudo apt-get remove nfspy
sudo apt-get remove ngrep
sudo apt-get remove nikto
sudo apt-get remove nipper-ng
sudo apt-get remove nishang
sudo apt-get remove nmap
sudo apt-get remove ohrwurm
sudo apt-get remove ollydbg
sudo apt-get remove onesixtyone
sudo apt-get remove ophcrack
sudo apt-get remove ophcrack-cli
sudo apt-get remove oscanner
sudo apt-get remove p0f
sudo apt-get remove pack
sudo apt-get remove padbuster
sudo apt-get remove paros
sudo apt-get remove pasco
sudo apt-get remove passing-the-hash
sudo apt-get remove patator
sudo apt-get remove pdfid
sudo apt-get remove pdf-parser
sudo apt-get remove pdgmail
sudo apt-get remove peepdf
sudo apt-get remove perl-cisco-copyconfig
sudo apt-get remove pev
sudo apt-get remove pipal
sudo apt-get remove pixiewps
sudo apt-get remove plecost
sudo apt-get remove polenum
sudo apt-get remove powerfuzzer
sudo apt-get remove powersploit
sudo apt-get remove protos-sip
sudo apt-get remove proxychains
sudo apt-get remove proxystrike
sudo apt-get remove proxytunnel
sudo apt-get remove ptunnel
sudo apt-get remove pwnat
sudo apt-get remove pyrit
sudo apt-get remove python-faraday
sudo apt-get remove python-impacket
sudo apt-get remove python-rfidiot
sudo apt-get remove python-scapy
sudo apt-get remove rainbowcrack
sudo apt-get remove radare2
sudo apt-get remove rake
sudo apt-get remove rcracki-mt
sudo apt-get remove safecopy
sudo apt-get remove readpst
sudo apt-get remove reaver
sudo apt-get remove rebind
sudo apt-get remove recon-ng
sudo apt-get remove recordmydesktop
sudo apt-get remove recoverjpeg
sudo apt-get remove redfang
sudo apt-get remove redsocks
sudo apt-get remove reglookup
sudo apt-get remove regripper
sudo apt-get remove responder
sudo apt-get remove rifiuti
sudo apt-get remove rifiuti2
sudo apt-get remove rsmangler
sudo apt-get remove rtpbreak
sudo apt-get remove rtpflood
sudo apt-get remove rtpinsertsound
sudo apt-get remove rtpmixsound
sudo apt-get remove sakis3g
sudo apt-get remove samdump2
sudo apt-get remove sbd
sudo apt-get remove scalpel
sudo apt-get remove scrounge-ntfs
sudo apt-get remove sctpscan
sudo apt-get remove sendemail
sudo apt-get remove set
sudo apt-get remove sfuzz
sudo apt-get remove sidguesser
sudo apt-get remove siege
sudo apt-get remove siparmyknife
sudo apt-get remove sipcrack
sudo apt-get remove sipp
sudo apt-get remove sipvicious
sudo apt-get remove skipfish
sudo apt-get remove sleuthkit
sudo apt-get remove smali
sudo apt-get remove smbmap
sudo apt-get remove smtp-user-enum
sudo apt-get remove sniffjoke
sudo apt-get remove snmpcheck
sudo apt-get remove socat
sudo apt-get remove sparta
sudo apt-get remove spectools
sudo apt-get remove spike
sudo apt-get remove spooftooph
sudo apt-get remove sqldict
sudo apt-get remove sqlitebrowser
sudo apt-get remove sqlmap
sudo apt-get remove sqlninja
sudo apt-get remove sqlsus
sudo apt-get remove sslcaudit
sudo apt-get remove ssldump
sudo apt-get remove sslh
sudo apt-get remove sslscan
sudo apt-get remove sslsniff
sudo apt-get remove sslstrip
sudo apt-get remove sslsplit
sudo apt-get remove sslyze
sudo apt-get remove statsprocessor
sudo apt-get remove stunnel4
sudo apt-get remove suckless-tools
sudo apt-get remove sucrack
sudo apt-get remove swaks
sudo apt-get remove t50
sudo apt-get remove tcpflow
sudo apt-get remove tcpflow-nox
sudo apt-get remove tcpick
sudo apt-get remove tcpreplay
sudo apt-get remove termineter
sudo apt-get remove tftpd32
sudo apt-get remove thc-ipv6
sudo apt-get remove thc-pptp-bruter
sudo apt-get remove thc-ssl-dos
sudo apt-get remove theharvester
sudo apt-get remove tlssled
sudo apt-get remove tnscmd10g
sudo apt-get remove truecrack
sudo apt-get remove twofi
sudo apt-get remove u3-pwn
sudo apt-get remove ua-tester
sudo apt-get remove udptunnel
sudo apt-get remove uniscan
sudo apt-get remove unicornscan
sudo apt-get remove unix-privesc-check
sudo apt-get remove urlcrazy
sudo apt-get remove vboot-kernel-utils
sudo apt-get remove vboot-utils
sudo apt-get remove vim-gtk
sudo apt-get remove vinetto
sudo apt-get remove vlan
sudo apt-get remove voiphopper
sudo apt-get remove volafox
sudo apt-get remove volatility
sudo apt-get remove vpnc
sudo apt-get remove wafw00f
sudo apt-get remove wapiti
sudo apt-get remove wce
sudo apt-get remove webacoo
sudo apt-get remove webscarab
sudo apt-get remove webshells
sudo apt-get remove weevely
sudo apt-get remove winexe
sudo apt-get remove wfuzz
sudo apt-get remove whatweb
sudo apt-get remove wifi-honey
sudo apt-get remove wifitap
sudo apt-get remove wifite
sudo apt-get remove windows-binaries
sudo apt-get remove wireshark
sudo apt-get remove wol-e
sudo apt-get remove wordlists
sudo apt-get remove wpscan
sudo apt-get remove wvdial
sudo apt-get remove xpdf
sudo apt-get remove xprobe
sudo apt-get remove xspy
sudo apt-get remove xsser
sudo apt-get remove xtightvncviewer
sudo apt-get remove yersinia
sudo apt-get remove zaproxy
sudo apt-get remove zenmap
sudo apt-get remove zim
